spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:mysql}:${DB_PORT:3306}/${DB_NAME:kcache_test}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    hikari:
      initializationFailTimeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

kcache:
  jpa:
    listener:
      enable: true
  state-storage:
    name: hazelcast
    hazelcast:
      host: ${HOSTNAME:localhost}
      discovery:
        type: TCP_IP
        tcp-ip:
          members:
            - test-app-first
    redis:
      host: redis
      port: 6379

logging:
  level:
    ru:
      nsu:
        manasyan:
          kcache: DEBUG
