version: "3.4"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    depends_on:
      - test-app-first
      - test-app-second
      - test-app-third
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: kcache_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - 3306

  test-app-first:
    depends_on:
      - mysql
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        PROPERTIES_PATH: /etc/dev/application-dev.yaml
    environment:
      - HOSTNAME=test-app-first
    ports:
      - "8081:8080"
    volumes:
      - ./application-dev.yaml:/etc/dev/application-dev.yaml

  test-app-second:
    depends_on:
      - mysql
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        PROPERTIES_PATH: /etc/dev/application-dev.yaml
    environment:
      - HOSTNAME=test-app-second
    ports:
      - "8082:8080"
    volumes:
      - ./application-dev.yaml:/etc/dev/application-dev.yaml

  test-app-third:
    depends_on:
      - mysql
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        PROPERTIES_PATH: /etc/dev/application-dev.yaml
    environment:
      - HOSTNAME=test-app-third
    ports:
      - "8083:8080"
    volumes:
      - ./application-dev.yaml:/etc/dev/application-dev.yaml
