# for tests only
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

kcache:
  jpa:
    listener:
      enable: true
  state-storage:
    name: hazelcast
    hazelcast:
      discovery:
        type: TCP_IP
        tcp-ip:
          members: localhost
    redis:
      host: localhost
      port: 6379


logging:
  level:
    ru:
      nsu:
        manasyan:
          kcache: DEBUG
