version: "3.2"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

#  test-app-first:
#    build: .
#    ports:
#      - "8081:8080"
#
#  test-app-second:
#    build: .
#    ports:
#      - "8082:8080"